### PR TITLE
more detailed build instructions [ci skip]

### PR DESCRIPTION
**Pull request by ranocha**

### CODE REVIEW

**Review by philipheinisch — COMMENTED** [review]
Looks great, but why did you remove the hint for the 'NVML' define?

**Comment by ranocha** [comment]
Right now, we have
```
IF(CUDA_FOUND)
  option(USENVML "Use NVML" ON)
ELSE()
  option(USENVML "Use NVML" OFF)
ENDIF()

IF(USENVML)
  MESSAGE(STATUS "Using NVML")
  add_definitions(-DUSENVML)
ENDIF()
```
Thus, it has no effect whether the user defines `USENVML` in the command line of CMake or not. Or did I miss something?

We have thus two alternatives: `USENVML` is set whenever CUDA is found (as it is now) or the user can disable `USENVML` explicitly. In that case, we have to add another check at the beginning, e.g. set `USENVML` as option with default value depending on `CUDA_FOUND`.

**Comment by philipheinisch** [comment]
It has no effect on CMake, but it could be defined manually in the actual source code to disable the corresponding feature. If CUDA was found, setting the CUDA includes would probably not cause any problems. On Windows systems, even if CUDA was detected during compilation, the NVML DLL is not always found at runtime. Hence the easiest solution would be to use the define in the source to disable NVML without having to deal with CMake. Long term this problem would best be solved by automatically detecting at runtime if CUDA and the necessary libraries are available and only use NVML if this is the case.

**Comment by ranocha** [comment]
Okay. I've added the sentence.

**Pull request merged**
