### PR TITLE
add output test

### PR DESCRIPTION
**Pull request by ranocha**
This test can be used to specify required output data.

### CODE REVIEW

**Comment by philipheinisch** [comment]
Is there some way to seperate all the tests from the main code? Apart from causing problems with the integrated VS2017 CMake features, IMHO it makes it harder and more confusing to understand the structure of the repository. Except from providing some usage examples, the tests are of no direct use to the normal users, are they?

**Comment by philipheinisch** [comment]
But it demonstrates a nice use case for toolkitICL: Testing OpenCL kernels in the context of CI without relaying on specific host applications. We might want to highlight that somewhere in the readme?

**Comment by ranocha** [comment]
> Is there some way to seperate all the tests from the main code?

I don't know. I'm used to the structure of Julia projects where having a `src` folder for the source code and a `test` folder for all tests is usual. Thus, the tests are clearly separated from the source code, I think.

**Comment by philipheinisch** [comment]
What about introducing some kind of 'make tests' to separate the make process? If someone just wants to use tookitICL the tests don't need to be compiled. This would also improve VS2017 integration.

**Comment by ranocha** [comment]
A possibility would be to configure this via `cmake`: If one wants to build the tests, the option `-DTESTS=ON` can be enabled manually and it is turned `OFF` otherwise. Do you have another suggestion to to add new targets to `cmake` optionally?

**Pull request merged**
